<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rock Paper Scissors</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="icon" href="../../img/icon.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="js/singleplayer-easy.js" type="application/javascript"></script>
    <link rel="stylesheet" href="/css/style.css">
    <script src="../js/keyCheck.js"></script>
    <script src="../js/difficulty.js"></script>


</head>

<body>

    <nav>
        <div class="nav-wrapper grey darken-4">
            <div class="nav-wrapper">
                <ul id="nav-mobile" class="left hide-on-med-and-down ">
                    <li><a href="javascript:javascript:history.go(-1)">Back</a></li>
                </ul>
                <a href="/" class="brand-logo center">RPS</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down ">
                    <li><a href="/">Home</a></li>
                    <li class=""><a href="/instructions">Instructions</a></li>
                    <li><a href="/credits">Credits</a></li>
                    <li><a href="/scoreboard">Scoreboard</a></li>
                </ul>
            </div>
    </nav>

    <div id="login"  class="hidden row">
        <form method="POST" action="loginIndex.php?actie=login" class="col s12">
          <div class="row">
            <div class="input-field col s6">
              <input placeholder="username" id="username" type="text" class="validate">
              <label for="username">Username</label>
            </div>
        
          </div>
          <div class="row">
            <div class="input-field col s6">
              <input id="password" type="password" class="validate">
              <label for="password">Password</label>
            </div> </div>
          <div class="row" ><a href="#">Forgot your password?</a></div>
         
          <button class="btn waves-effect waves-light" type="submit"  value="Login" name="login" name="action">Login
            <i class="material-icons right">send</i>
          </button>
        
        </form>
      </div>


     <div id="register" class="row ">
      <form method="post" action="/register" class="col s12">
        <div class="row">
          <div class="input-field col s6"> 
            <input placeholder="Username" name="username" id="username" type="text" class="validate" required >
            <label for="first_name">Username</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <input name ="password" id="password" type="password" class="validate" required>
            <label for="password">Password</label>
          </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
              <input name ="confirmpassword" id="confirmpassword" type="password" class="validate" required>
              <label for="confirmpassword">Confirm Password</label>
            </div>
          </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="email" name ="email" type="email" class="validate" required>
            <label for="email">Email</label>
          </div>
        </div>
        <button class="btn waves-effect waves-light" type="submit"  value="register" name="register" name="action">Register
            <i class="material-icons right">send</i>
          </button>
      </form>
    </div>
    <audio src="../Audio/RPS.wav" id="my_audio" loop="loop"></audio>
    <button id="mute" class="btn-floating btn-large waves-effect waves-light grey darken-3 large material-icons">volume_off</button>
    <script src="../js/sounds.js"></script>

</body>

</html>



