<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rock Paper Scissors</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="icon" href="/img/icon.png">

    <script src="../js/javascript.js"></script>
    <link rel="stylesheet" href="/css/style.css">
</head>

<body class="indexBackground">

     <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav>

    <div class="indexButtons">
        <ul>
            <li><a href="/mode" class="waves-effect waves-light btn">Play</a></li>
            <li><a href="/instructions" class="waves-effect waves-light btn">Instructions</a></li>
            <li><a href="/credits" class="waves-effect waves-light btn">Credits</a></li>
            <li><a href="/scoreboard" class="waves-effect waves-light btn">Scoreboard</a></li>
        </ul>
    </div>
    </div>
    
    
</body>
</html>